// JavaScript Document
document.writeln("<nav class=\'navbar navbar-default\' role=\'navigation\'>");
document.writeln("        <div class=\'container-fluid\'>");
document.writeln("          <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'#nav-navbar-collapse\'> <span class=\'sr-only\'>切换</span> <span class=\'icon-bar\'></span> <span class=\'icon-bar\'></span> <span class=\'icon-bar\'></span> </button>");
document.writeln("            <a class=\'navbar-brand\'>Air</a> </div>");
document.writeln("          <div class=\'collapse navbar-collapse\' id=\'nav-navbar-collapse\'>");
document.writeln("            <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("              <li><a href=\'../index.html\'>主页</a></li>");
document.writeln("              <li> <a href=\'topic.html\'>帖子</a></li>");
document.writeln("              <li class=\'dropdown\'> <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>关于<b class=\'caret\'></b> </a>");
document.writeln("                <ul class=\'dropdown-menu\'>");
document.writeln("                  <li><a href=\'../about/connext.html\'>联系我们</a></li>");
document.writeln("                  <li><a href=\'../about/team.html\'>团队</a></li>");
document.writeln("                  <li><a href=\'../about/thanks.html\'>鸣谢</a></li>");
document.writeln("                </ul>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </nav>");